# Generated by Django 4.2.1 on 2023-05-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
